---

plugins:
  - jest

env:
  node: true
  jest: true

parserOptions:
  ecmaVersion: 11
  sourceType: module

extends:
  - 'airbnb-base'
  - 'plugin:jest/recommended'

rules:
  no-console: 0
  import/prefer-default-export: 'off'
  import/extensions: 0 # FIXME: remove when rule will be adjusted for new nodejs version
